name: Testnet deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment: develop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build
        env:
          CI: false
          VITE_API_URL: ${{ secrets.API_URL }}
          VITE_DONATION_ADDRESS: ${{ secrets.DONATION_ADDRESS }}
          VITE_NETWORK: mumbai
          VITE_BETA_CONTRACT: "0x2fa133F8A7C9db0285BfF9984c29316482d9834d"
          VITE_SESSION_CONTRACT: "0xA603Ce9Fa6915fe560d508F5060D1387C4304BE7"
          VITE_FARM_CONTRACT: "0xB554607D04D6C3EecAb4Cd19A0cF8218BD82fff0"
          VITE_INVENTORY_CONTRACT: "0xfd3b40980aF8706D77C61782eA1ecEFF7600e344"
          VITE_TOKEN_CONTRACT: "0x1D24F82b5d9d72450C2ed065F51827Eb280FFA38"
          VITE_WISHING_WELL_CONTRACT: "0xdc9B03A1b83328a02e42B707F077Ab33Cf079415"
          VITE_PAIR_CONTRACT: "0xaE42EA9864C36820627068a11959915f817ce809"
          VITE_DISCORD_REDIRECT: "https://sunflower-land.com/testnet/"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.5.9
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./dist/ s3://sunflower-land.com/testnet --delete

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./dist/ s3://www.sunflower-land.com/testnet --delete
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
